### ISSUE TITLE
Feature Request: Fixed header for the top part of the form creation and editing pane

### ISSUE THREAD

**Issue by StefanoRausch** [danielo515/obsidian-modal-form#11]
One has to scroll back to the top to view the main descriptive part of the forms and for adding new fields or closing the forms -- relates to https://github.com/danielo515/obsidian-modal-form/issues/8.

![image](https://github.com/danielo515/obsidian-modal-form/assets/1460531/ff86b378-e098-42ab-99af-e594ed392bc8)

I suggest to make the "header" part fixed, i.e., not scrollable.

**Comment by danielo515** [comment]
Hey, thanks for the feedback. Do you mind explaining in which context you need to scroll? In your screenshot you can see all the headers of each field. Or do you mean that, when the number of fields is long you loose the context of which form you are editing?

**Comment by StefanoRausch** [comment]
Exactly the latter one. If the form has a lot of fields, the top part (header) scrolls up. 😉

**Comment by StefanoRausch** [comment]
Fantastic, it works really well. Thank you for addressing the issue!

**Comment by danielo515** [comment]
Anytime!
