### ISSUE TITLE
[Feature request] tag suggest input type

### ISSUE THREAD

**Issue by danielo515** [danielo515/obsidian-modal-form#118]
An input type that allows to pick one or more tags.
Maybe with an option to filter out tags?

**Comment by zeltak** [comment]
would also LOVE that option, would make this perfect for me..pretty please with sugar on top? :) :)

**Comment by danielo515** [comment]
@zeltak in this initial version, there is no configuration, because I didn't saw the need. Maybe a way to exclude tags would be required, or an option to remove the `#` prefix on them. Please let me know your thoughts.

**Comment by zeltak** [comment]
This is SOOOO EPIC :) thank you so much for this , honestly this is the best plugin since ive started using obsidian a few years ago!!

one thing though is that I see it currently does not put the input into the YAML header but rather capture below the title, am I missing something or is YAML not supported yet? since obsidian moved fully to YAML properties I moved my thousand of files to use that

here is an example of the current way the plugin saves 

```
# inbox
- [ ] tag:: "#china","#asia"
```

VS the way I (and obsidian save in YAML)

```
---
tags:
  - china
  - asia
status: 
---
# inbox
```

am I missing something?

thx so much for your epic work @danielo515 !

**Comment by danielo515** [comment]
Can you share with me the template you are using so I can look into it
better?

**Comment by zeltak** [comment]
sure , im just using the base obsidian YAML header though, but here is an example .md file

```
---
tags:
  - CQ
  - asia
  - noodle
  - chicken-thigh
status: 5
rating: 4
location: 
counter: 
created: 20220318
url: https://thewoksoflife.com/ginger-scallion-hokkien-noodles/
---
# food.cook.ginger scallion hokkien noodles

[Hokkien Noodles with Chicken, Ginger & Scallion - The Woks of Life](https://thewoksoflife.com/ginger-scallion-hokkien-noodles/)

> [!ABSTRACT]
> For the chicken:
> 8 ounces boneless skinless chicken thighs (cut into thin strips; can substitute boneless skinless chicken breast)
> 1 teaspoon cornstarch
> 1 teaspoon vegetable oil
> 1 teaspoon light soy sauce
> To finish the dish:
> 3 tablespoons vegetable oil
> 6 slices ginger
> 8 scallions (julienned)
> 1 red chili (sliced, optional)
> 1 pound cooked hokkien noodles or fresh lo mein noodles
> 2 tablespoons Shaoxing wine (can substitute clear rice wine or dry sherry)
> 1 1/2 tablespoons light soy sauce
> 2 teaspoons dark soy sauce

```

thx so much for all your amazing work, its truly appreciated!

**Comment by danielo515** [comment]
Hey @zeltak , thank you for your kind words.
I was asking for the template where you make use of modal-form to create the output note. The way you report the plugin is saving is only if you tell it to render it like dataview. If you select to render the result as frontmatter, here is an example of what I'm getting:

```yaml
toggle: false
multi_books: []
select: first
multi_2: []
multi_select_dataview: []
select-fail: ""
tags:
  - "#book"
  - "#person"
  - "#person/Química"
```

Or you are referring to the `#` prefix? If so, that is what I was asking you in my first message, about how good or bad it looks

**Comment by danielo515** [comment]
In any case, I think the leading `#` does not look right, so I just removed it in the latest version. Let me know if it is what you expected

**Comment by zeltak** [comment]
Ahh @danielo515  I see, thx for clarifying. 

I agree the `#` is not needed and glad you removed it :)

what im still not clear of is where does one define the rendering part? I can't see it in the plugins option or when I build the template see:

![CleanShot 2023-11-23 at 08 09 24@2x](https://github.com/danielo515/obsidian-modal-form/assets/498410/822ca72e-0414-4211-a903-0a163fe6254f)

here is the simple capture modal template:

```
{
  "title": "mtest",
  "name": "mtest",
  "customClassname": "",
  "fields": [
    {
      "name": "tag",
      "label": "tag",
      "description": "tags",
      "input": {
        "type": "tag"
      }
    },
    {
      "name": "status",
      "label": "status",
      "description": "status",
      "input": {
        "type": "number"
      }
    },
    {
      "name": "ratings",
      "label": "ratings",
      "description": "ratings",
      "input": {
        "type": "number"
      }
    }
  ],
  "version": "1"
}

```

thx again, really loving this!

**Comment by danielo515** [comment]
You define it in the templater template that's why I was asking for it 😄 

Let me know if following this example makes ting works as you expect:
https://github.com/danielo515/obsidian-modal-form/blob/master/examples/basic%20template%20example.md?plain=1

As you can see, it adds the result of the form to the frontmatter. Is that similar to what you are doing?

**Comment by zeltak** [comment]
awesome works like a charm with templatar!!

thx so much @danielo515 !!

Z

**Comment by danielo515** [comment]
Happy to see that it finally works for you.
