### ISSUE TITLE
Import forms

### ISSUE THREAD

**Issue by fieldrabbit21** [danielo515/obsidian-modal-form#123]
I like to be able to export a form that I have created and share the exported form with others. They then have the ability to import the form

BTW: Thank you for this great plugin!

**Comment by danielo515** [comment]
The good news is that you can already export it. What is missing is the import part. What is your desired workflow? You want a button to import a form that opens a modal, or navigates to a different section? I'm also curious about who are you sharing it with, if you can tell me.

> BTW: Thank you for this great plugin!

Thank you for the nice words.

**Comment by fieldrabbit21** [comment]
> The good news is that you can already export it. What is missing is the import part. What is your desired workflow? You want a button to import a form that opens a modal, or navigates to a different section? I'm also curious about who are you sharing it with, if you can tell me.
> 
> > BTW: Thank you for this great plugin!
> 
> Thank you for the nice words.

hi! yes, a simple Import button would be sufficient.

in the first place I would be sharing it with myself, for use on my phone, next to my laptop.

thanks again for a useful plugin!
