### ISSUE TITLE
[Feature request] Text / Inscruction panel

### ISSUE THREAD

**Issue by Lennart-Lucas** [danielo515/obsidian-modal-form#124]
It would be handy to have a way to display text of instructions without having an input field tied to it.
Something akin to QuickAdd's infoDialog where you pass in a string in the definition which the user gets to see.
with the full width of the form but without input field.

This would be especially helpfull with more complex workflows where you want to display previously selected or generated
information.

**Comment by Lennart-Lucas** [comment]
The QuickAdd info dialog was just an example, it basically displays a given text to the user with an okay button.
It would be amazing to have something similar to put into the form.

 
![Screenshot 2023-11-08 002000](https://github.com/danielo515/obsidian-modal-form/assets/37398342/9febf264-1d7e-4496-b059-60256ac66d32)

**Comment by danielo515** [comment]
Cool. Will add something similar as next feature

**Comment by danielo515** [comment]
@Lennart-Lucas I'm working on this and I have doubts about certain details.
For now, the best way to do this (the most flexible one at least) is that the documentation block will be a function that gets all the form values, and it should return a string that will be rendered in the documentation block.
However, I am not sure about the following:

- Should this block have the label visible? Just like any other form input, with the label on top and the form text below?
- Do you think returning a single string is enough? I can expect 2 strings and put the first one in the description, and the second one in the body. I'm not sure either about this

Here is the current implementation, where all I'm doing is rendering the returned string as is, letting the form label and form description just like the rest of the other blocks:

<img width="521" alt="Screenshot 2023-12-19 at 10 22 11" src="https://github.com/danielo515/obsidian-modal-form/assets/2270425/8c5b063a-a839-4cff-9712-0d6185a2179f">
If you have any thoughts, let me know

**Comment by Lennart-Lucas** [comment]
I've played around with this and it seems great!

The label is optional, so if people want to use it then it's there if not then it's not a hassle.

One string for the text itself should be sufficient if the formatting works. As it stands the newline (`\n`) seems to be ignored by the form? When I try the example form or implement it myself the newlines get skipped. If the form correctly interprets the newline it's possible to create paragraphs and format text.

**Comment by danielo515** [comment]
I think I overlooked this, and I may need to change to a html formatted
text or something like that. While I explore this, can you try using <br>
instead of newlines? To see if It works.

**Comment by Lennart-Lucas** [comment]
I have tried that, but HTML doens't seem to get parsed at all.

HTML such as <br/> or <b> is treated like regular text and gets printed as such.
For instance: `<b>Hello ${form.name}!</b><br/>Your best friend is ${form.best_fried}`
Gets printed as: "<b>Hello undefined</b><br/>Your best friend is "

**Comment by danielo515** [comment]
Ok. I will give it a go as pre-formatted block of text

**Comment by danielo515** [comment]
@Lennart-Lucas I just added support for html in the returned string.
Can you try again using <br> and any other tag you may wish? like `<b>Hello</b>`

**Comment by Lennart-Lucas** [comment]
Both the tags and new lines work, thanks again.
