### ISSUE TITLE
[BUG] - very specific bug - multiselect dataview queries with #what and aliases

### ISSUE THREAD

**Issue by brianbecsi** [danielo515/obsidian-modal-form#131]
Hi - I'm trying to query notes with my `#what` tag. 

`dv.pages('#what').map(p => p.aliases)`

* Works in dataview
* Works in dataview query type
* does not work in multiselect dataview query

+ other tags do work
`dv.pages('#what').map(p => p.file.name)` works.

Is this a keyword conflict?

**Comment by brianbecsi** [comment]
Forgive me, this should be a bug not an enhancement, but I don't know how to remove the enhancement label.

**Comment by brianbecsi** [comment]
Must have been a typo - thanks.

**Comment by danielo515** [comment]
You mean it is fixed?
