### ISSUE TITLE
[BUG] js quickadd - No cancel button, pressing the ESC on the form just aborts the elaboration.

### ISSUE THREAD

**Issue by morettimarco** [danielo515/obsidian-modal-form#133]
I've built a script for quickadd, with the purpose of summarizing the activities I'm working on weekly, that works in the following way

1. Presents a form to capture the main activity
2. Formats the collected data and adds it to a document variable
3. Ask the users to define the follow-up actions for that activity using a while loop
4. When a user presses cancel or the ESC key, the scripts present a prompt to insert a new activity
5. If the user accepts to insert a new item, the form is shown again, otherwise the content of the document variable is printed on the file

I'm having a the following issu issue: if the user presses the ESC key on the form, the script just quits, and I'm unable to handle it and save the content of the document variable on a file.
This doesn't happen with the quickAddApi.inputPrompt, and therefore I suspect it's a issue with modalforms.

I've tried in several ways to handle it, but without any success.
Is there a way to manage this or adding a “cancel” button on the form that could be handled?

Here is my script:

```js quickadd

let pulseCompleted = false;
let document ='';

while (!pulseCompleted)
{
	const values ={
	  Urgency: 1,
	  Importance: 1,
	}; //Default Values for the form

	const modalForm = app.plugins.plugins.modalforms.api; 
	const result = await modalForm.openForm('Pulse Item', { values: values }); 
	document += result.asString
	('# {{ItemName}}\n- Urgency: {{Urgency}}\n- Importance: {{Importance}}\n- Progress: {{Progress}}\n\n====Detailed Status====\n{{DetailedStatus}}\n');

	document += '====Action Items====\n'; 

	let selectMore = true;
	while (selectMore) {
	let newItem = await this.quickAddApi.inputPrompt("Add action item", "Text of the action");
	    if (!newItem){
	        // If the user presses ESC or closes the suggester, exit the loop
	        selectMore = false;
	    }
	    else {
	    document += '- [ ] '+newItem+'\n'; 
	    }
	}
	
	if (!confirm("Insert a new Item?")) 
	{
		pulseCompleted = true;
	}
	else
	{
		document += '\n\n';
                console.log(document);
	}
}

return document;

```

**Comment by danielo515** [comment]
Yes, there is no cancel handler.
I have it on the pipeline, but I never needed it in practice, so I never implemented it. I'll take this as a feature request to implement the cancel button, so you can have a graceful exit of a form without submitting things

**Comment by danielo515** [comment]
This should be fixed by now. Please open a new issue if you have further problems.
