### ISSUE TITLE
[BUG]  result.get is not a function

### ISSUE THREAD

**Issue by the1gofer** [danielo515/obsidian-modal-form#162]
Templater throws the following error:  

```
plugin:templater-obsidian:61 Templater Error: Template parsing error, aborting. 
 result.get is not a function
```

**To Reproduce**
```
const modalForm = app.plugins.plugins.modalforms.api;
const result = await modalForm.openForm("new-case");
let leadDefendant = result.get("defendants");
```

```
{
  "title": "New Case",
  "name": "new-case",
  "customClassname": "case",
  "fields": [
    {
      "name": "defendants",
      "label": "Defendants",
      "description": "",
      "isRequired": true,
      "input": {
        "type": "multiselect",
        "folder": "TCPA/1 - Cases/52 - Entities of Interest",
        "query": "",
        "multi_select_options": [],
        "source": "notes"
      }
    },
    {
      "name": "attorney",
      "label": "Attorney",
      "description": "Attorney",
      "isRequired": false,
      "input": {
        "type": "multiselect",
        "source": "notes",
        "folder": "TCPA/1 - Cases/52 - Entities of Interest",
        "query": "",
        "multi_select_options": []
      }
    },
    {
      "name": "related parties",
      "label": "Related Parties",
      "description": "Related Parties",
      "isRequired": false,
      "input": {
        "type": "multiselect",
        "source": "notes",
        "folder": "TCPA/1 - Cases/52 - Entities of Interest",
        "query": "",
        "multi_select_options": []
      }
    }
  ],
  "version": "1"
}
```

**Expected behavior**
assign value of defendants to variable

**Additional context**
It might be something I'm doing, but I don't see it.

**Comment by the1gofer** [comment]
1.29

**Comment by the1gofer** [comment]
Ok, works after updating.

**Comment by the1gofer** [comment]
for multi select, are their any methods to get just the text, or individual results?  for example result.get("defendants")[0] or result.get("defendants").text.  something like that.

**Comment by danielo515** [comment]
The get method takes an optional mapping function you can use to modify the values. So, if you have your values "nested" in an object, you can do something like this.

Imagine this is just a single value but want the text property:
```ts
result.get('something', (thing) => thing.text)
```

If you have several objects and want to join them
```ts
result.get('something', (thing) => thing.join(', ')
```

If you want to join and transform them at the same time, you can do this:
```ts
result.get('somethings', (things) => thing.map((i) => `[[${i}]]`).join(', '))
```

**Comment by the1gofer** [comment]
so 

let caseName = result.get('case-link')
works, and gives a result like '["something"]'

however
`let caseName = result.get('case-link', (thing) => thing.text)`
gives a result of "undefined"

**Comment by the1gofer** [comment]
ok so it looks like the problem is .text

so 
`let caseName = result.get('case-link', (thing) => thing)`

has the desired result

**Comment by danielo515** [comment]
That is correct.
The mapping/transform function is optional,in case you don't provide it what you get back is just the value.
On top of that, the mapping function is only called if the value exists, and it will get the plain value, nothing wrapping it.

I'm working in a more advanced and convenient API ,you can take a look at the documentation in the PR if you have to see a preview of how it will work: #178

**Comment by danielo515** [comment]
I see how my first comment could lead to confusion. There is no situation right now where you will get an object with a text value, so my first example was a bit confusing.
For completeness , you can also call it with just the key name you want 

```ts
result.get('something')
```
Or a more logical transformation could be
```
result.get('something', (it) => it.toUpperCase())
```
