### ISSUE TITLE
Bug: Cannot update to the latest version

### ISSUE THREAD

**Issue by StefanoRausch** [danielo515/obsidian-modal-form#23]
![image](https://github.com/danielo515/obsidian-modal-form/assets/1460531/eb4ca838-00e3-45ed-965e-06a2ebf12974)

**Comment by danielo515** [comment]
Can you try again? The tagging happens a bit earlier than the upload of the assets, you may tried in the meantime.

**Comment by StefanoRausch** [comment]
Still no dice.

**Comment by danielo515** [comment]
Do you know to which version is it trying to update to ?

**Comment by danielo515** [comment]
Ok, I think the tool that I use to create releases automatically has started to mess things. I manually fixed it and it is updating nicely for me

**Comment by StefanoRausch** [comment]
Yep, it did update now -- thanks!

**Comment by danielo515** [comment]
Do you have an automated flow? :😄: I already fixed it, please take a look

**Comment by StefanoRausch** [comment]
I have not. just BRAT checking for the update and warning me in case there is a problem.

The update went through. Thank you.
