### ISSUE TITLE
[Feature request] Dataview Input add additional items

### ISSUE THREAD

**Issue by kevinkickback** [danielo515/obsidian-modal-form#249]
I would like the ability to add/push additional entries to the array returned by the dataview input.

For example if I have a folder called "characters" with three notes inside: Person1, Person2, & Person3, I could use dv.pages('"characters"').file.name to return the three file names and somehow add a 4th option called "Everyone" to the list like:

- Person1
- Perosn2
- Person3
- Everybody

**Comment by danielo515** [comment]
This should be already possible. Will try to write an example as soon as I
can

**Comment by danielo515** [comment]
Yes, it is possible and it is very simple.
The dataview field it is just some expression that gets evaluated. It can be a single dataview command, or it can be more things, like concatenation of results like this:

```ts
['1','2', ...dv.pages('#programming').title]
```

<img width="737" alt="Screenshot 2024-05-08 at 15 08 02" src="https://github.com/danielo515/obsidian-modal-form/assets/2270425/90db68d3-0f07-4a66-8b83-3043976542ca">



Take advantage of the preview to experiment a bit with what you will get in the input
<img width="929" alt="Screenshot 2024-05-08 at 15 07 15" src="https://github.com/danielo515/obsidian-modal-form/assets/2270425/684d3cf6-a862-4cf6-8df9-cea11dbbd97e">
