### ISSUE TITLE
openForm should return a value if the user cancels the form

### ISSUE THREAD

**Issue by TfTHacker** [danielo515/obsidian-modal-form#256]
**Is your feature request related to a problem? Please describe.**
When calling the openForm method, if the user cancels the form (clicks he x to close it), it does not return a value (at least in templater). So there is no way of responding if the user interrupts the workflow. 

**Describe the solution you'd like**
openForm should still return a status indicating if the user closes the form without clicking submit. This could also be returning a null value.

**Comment by danielo515** [comment]
related to #133
