### ISSUE TITLE
[BUG] Deleting the value of a number field doesn't work right

### ISSUE THREAD

**Issue by anonhostpi** [danielo515/obsidian-modal-form#274]
Deleting the value of a number field causes it to return the undeleted value

**To Reproduce**
Steps to reproduce the bug:
1. Enter a value into a number field
2. Highlight the entire value
3. Delete it
4. Submit modal

**Expected behavior**
Value should be undefined

**Actual behavior:**
Value is the undeleted number

**Comment by danielo515** [comment]
This should have been fixed in 1.47.0
