### ISSUE TITLE
[BUG] Multiselect Dataview values not offered to choose from

### ISSUE THREAD

**Issue by zanodor** [danielo515/obsidian-modal-form#280]
**Describe the bug**

Normal Dataview entry seems to work but that allows only one value to be entered. Multiselect DV doesn't work.

**To Reproduce**

Make a form with Multiselect Dataview entry querying a property e.g. `[...new Set(dv.pages("").flatMap(p => p.somepropertyName || []))].sort((a, b) => a.localeCompare(b))`

**Behavior**

While making the form, Dataview query results are correctly shown. When the form is used in note creation process, no values are offered – not even one.

**Expected behavior**

All value results created with Dataview are offered to choose from, allowing multi values to be selected as well.

**Current workaround**

Use Multiselect static solution and add all currently available Dataview results to data.json file manually.

**Comment by danielo515** [comment]
I tested that on my vault, and it works. I had to change the propety name to one that exist on my vault (in this case, tags) but everything works as I expect. May you tell me what is in that property name?
<img width="610" alt="Screenshot 2024-06-22 at 10 52 29" src="https://github.com/danielo515/obsidian-modal-form/assets/2270425/21edca18-96b9-47ab-bdb7-dd9ac94d3f69">
<img width="1429" alt="Screenshot 2024-06-22 at 10 52 20" src="https://github.com/danielo515/obsidian-modal-form/assets/2270425/9d7e720d-e334-405a-aa91-cdbbcfce3370">

**Comment by danielo515** [comment]
Happy to see you found the problem!
