### ISSUE TITLE
[Feature request] add current date or time in result

### ISSUE THREAD

**Issue by louwelyn-jeremy** [danielo515/obsidian-modal-form#286]
thank you for your work!
i have an issue with this plugin for make log to my journal.
i use Quick addand i can add log like this one:
log:: ☑📡 my text [[link to project]]
but i want to add the current time ... how can i do that ?

**Comment by danielo515** [comment]
this is (if I understand it correctly) the same as #269, but a bit more specific to date.
May you share the template you are using?

**Comment by louwelyn-jeremy** [comment]
no problem
### from modal forms

{
  "title": "ajouter un log journalier",
  "name": "LOG",
  "fields": [
    {
      "name": "type",
      "label": "type de log",
      "description": "Séléctionner le type de log",
      "isRequired": true,
      "input": {
        "type": "select",
        "source": "fixed",
        "options": [
          {
            "value": "log:: ☑💼",
            "label": "Projet"
          },
          {
            "value": "log:: ☑📡",
            "label": "Perimetre"
          }
        ]
      }
    },
    {
      "name": "log",
      "label": "info",
      "description": "indiquer ici l'information à noter",
      "isRequired": true,
      "input": {
        "type": "text"
      }
    },
    {
      "name": "lien",
      "label": "en rapport avec",
      "description": "choisir le projet, le périmètre",
      "isRequired": false,
      "input": {
        "type": "dataview",
        "query": "dv.pages('\"KMS_jeremy/GTD/GTD-Dom. resp\" or \"KMS_jeremy/GTD/GTD-objectifs\"or \"KMS_jeremy/GTD/GTD-projets\"').file.name"
      }
    }
  ],
  "version": "1",
  "template": {
    "createCommand": true,
    "parsedTemplate": []
  }
}

### from quick add
`
```js quickadd
	const modalForm = app.plugins.plugins.modalforms.api;
	const result = await modalForm.openForm('LOG');
	return result.asString('{{type}} {{log}} [[{{lien}}]]');
```
`

**Comment by louwelyn-jeremy** [comment]
I found something from #269 and the quick add documentation:
in can use a function in quick add to find the actual hour with  `window.moment().format("HH:mm");`
this my code now (i make some change)
# from modal form
{
  "title": "ajouter un log journalier",
  "name": "LOG",
  "fields": [
    {
      "name": "type",
      "label": "type de log",
      "description": "Séléctionner le type de log",
      "isRequired": true,
      "input": {
        "type": "select",
        "source": "fixed",
        "options": [
          {
            "value": "log:: ☑💼",
            "label": "Projet"
          },
          {
            "value": "log:: ☑📡",
            "label": "Perimetre"
          }
        ]
      }
    },
    {
      "name": "log",
      "label": "info",
      "description": "indiquer ici l'information à noter",
      "isRequired": true,
      "input": {
        "type": "text"
      }
    },
    {
      "name": "lien",
      "label": "en rapport avec",
      "description": "choisir le projet, le périmètre",
      "isRequired": false,
      "input": {
        "type": "dataview",
        "query": "dv.pages('\"KMS_jeremy/GTD/GTD-Dom. resp\" or \"KMS_jeremy/GTD/GTD-objectifs\"or \"KMS_jeremy/GTD/GTD-projets\"').file.link"
      }
    }
  ],
  "version": "1",
  "template": {
    "createCommand": true,
    "parsedTemplate": []
  }
}
# from quickadd
````js quickadd
	const modalForm = app.plugins.plugins.modalforms.api;
	const result = await modalForm.openForm('LOG');
	const temps = window.moment().format("HH:mm");
	return result.asString('{{type}} ||')+ temps + result.asString('|| {{log}} {{lien}} \n');
````
the result: 

log:: ☑📡 ||09:04|| my text  [[path/to/my note.md|my note]]

**Comment by danielo515** [comment]
That is is correct code. When I get back to home later I will provide you a
simpler version if you like it

**Comment by danielo515** [comment]
So, you can write that code like this, using a single [javascript template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

```js
	const modalForm = app.plugins.plugins.modalforms.api;
	const result = await modalForm.openForm('LOG');
	const temps = window.moment().format("HH:mm");
	return result.asString(`{{type}} || ${temps} || {{log}} {{lien}} \n`);
```

I feel really tempted to document this under advanced usecases.
If you are happy with the outcome, can we close the issue?

**Comment by louwelyn-jeremy** [comment]
You can close the issue, thank you.
Sorry, I'm a newbie in javascript

**Comment by danielo515** [comment]
No worries, we've all been there
