### ISSUE TITLE
Unnecessary logging to console

### ISSUE THREAD

**Issue by czenk** [danielo515/obsidian-modal-form#301]
Release 1.48  introduced multiple calls to console.log() in the developer console.
Persisting in release 1.49

Example:
{_tag: 'Right', right: true}

**To Reproduce**
Steps to reproduce the bug:
1. Open Developer Console
2. Call a modal form

**Expected behavior**
In its default configuration the developer console should only show error messages, debug messages should not be shown.

**Comment by danielo515** [comment]
Yeah, I agree. Having a configurable debugging is something I wanted to add for some time. I'm tired of adding logging and removing it before releasing.

**Comment by czenk** [comment]
> Yeah, I agree. Having a configurable debugging is something I wanted to add for some time. I'm tired of adding logging and removing it before releasing.

Believe me, I feel your pain - same here (wouldn't have spotted it otherwise ;-). I guess the most efficient way is to look care for each other. 
Thanks for all your effort and for maintaining your plugin.

**Comment by danielo515** [comment]
this was hotfixed already
