### ISSUE TITLE
[Feature request]conditional for more fields

### ISSUE THREAD

**Issue by erduotong** [danielo515/obsidian-modal-form#316]
**Is your feature request related to a problem? Please describe.**

When I use it, I want to try to implement a function:
Other texts appear one by one based on the content in the multi select
However, I found that the conditional feature is not applicable to multi select

**Describe the solution you'd like**

Introduce the same method as select for other components when selecting and judging multi select, such as' start with ', etc
﻿
**Additional context**

Thank you for creating this wonderful plugin

**Comment by danielo515** [comment]
Probably related to #332
