### ISSUE TITLE
[Feature request] Expose select form (from All form) in javascript

### ISSUE THREAD

**Issue by yinlokc** [danielo515/obsidian-modal-form#318]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Expose select form (from All form) in javascript
**Additional context**

**Comment by danielo515** [comment]
Sorry, I don't understand the request

**Comment by yinlokc** [comment]
const modalForm = app.plugins.plugins.modalforms.api;
const result = await modalForm.openForm('example-form');

currently, we will need to explicitly input 'example-form' in order to trigger the form, is there any way to trigger a drop down box, such that I can select which form to trigger (similar to the case when we select "Edit Form")? And the follow up question will be any way to trigger the template to define the output format other than just e.g asDataviewProperties now. Thanks.

**Comment by danielo515** [comment]
Ok, now I understand what do you mean.
This (or something similar) is honestly something I wanted to do for some time.
Are you familiar wit template autocomplete? when you type `tp.` it offers a list of possible completions. Will that work?
Also, there is the "template builder" that eases the process of creating templates that use existing forms. Have you tried it? You can click 'open in template builder' next to any form definition and it will help you create a template for that form.

**Comment by yinlokc** [comment]
Thanks. Yes, I can implement through tp. just would like to explore if there is any function I can leverage. My idea is to build a function that 
Step 1: Prompt to ask which form I want to use
Step 2: Output the string that generated based on the template (that associated with the form)

**Comment by danielo515** [comment]
I was not suggesting to create a template to fulfill this usage scenario (although, it is doable and something I encourage).
I was referring to the same functionality that templater has where you get suggestions of what templater methods you can use. Here is an screenshot for reference:
![Screenshot 2024-09-09 at 13 02 20](https://github.com/user-attachments/assets/1fe70490-e457-4eff-8541-67331a7479c0)

**Comment by yinlokc** [comment]
Got it. Thanks for your reply.

**Comment by danielo515** [comment]
By the way, what you were requested was being tracked here (I think that is what you were asking for initially):
 https://github.com/danielo515/obsidian-modal-form/issues/143

**Comment by danielo515** [comment]
Also related, which is even closer to your original request is this:
https://github.com/danielo515/obsidian-modal-form/issues/171
