### ISSUE TITLE
[Feature request] How to adjust the width of prompt? Can it be done through css?

### ISSUE THREAD

**Issue by yinlokc** [danielo515/obsidian-modal-form#322]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As discussed. 
**Additional context**

**Comment by danielo515** [comment]
I am not sure. You can define a CSSClass to attach to each form, but I don't know if that will let the modal to be modified in terms of width. Maybe if you restrict the width of the form that will automatically make the modal smaller. Worth a try if you want

**Comment by yinlokc** [comment]
I finally can adjust the width with the following css

.modal:has(.custom-modal) {
   
    padding: 20px !important;               /* Example padding */
    border-radius: 10px !important;         /* Example border radius */
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1) !important; /* Example box shadow */
    width: 100% !important;                   /* Example width */
    max-width: 800px !important;             /* Example max width */
}
