### ISSUE TITLE
[BUG] The value of ResultValue Map function on multiselect is not an array

### ISSUE THREAD

**Issue by josephgarnier** [danielo515/obsidian-modal-form#331]
In my form `create-article-page`, I have a field `category` of type "multiselect with dataview source" that return, as expected, an array:

```json
{
    "value": [
        "#categorie/espace-article/activites-en-informatique",
        "#categorie/espace-article/anthropologie",
        "#categorie/espace-article/architecture-informatique"
    ],
    "name": "category"
}
```

I want to remove all `#`, but in using the map function of `ResultValue` with the code bellow, I got a javascript error in `map()` because `tag` is not a string but an array.

```javascript
  const modalForm = app.plugins.plugins.modalforms.api;
  const result = await modalForm.openForm("create-article-page");

  const category = result
    .getValue("category")
    ?.map((tag) => tag.replace("#", ""));
```
Indeed, if you try to log `map()`:

```javascript
const category = result
  .getValue("category")
  ?.map((tag) => console.log("My tag is: " + tag);
```

The **current result is** a single iteration displaying:

```text
my tag is: #categorie/espace-article/activites-en-informatique,#categorie/espace-article/anthropologie,#categorie/espace-article/architecture-informatique
```

**While it is expected** three iterations:

```text
my tag is: #categorie/espace-article/activites-en-informatique
my tag is: #categorie/espace-article/anthropologie
my tag is: #categorie/espace-article/architecture-informatique
```

ps: thank you very much for this very useful plugin.

**Comment by danielo515** [comment]
Hello @josephgarnier , and sorry for the confusion. Good bug report by the way.
However, this is not a bug, it's intended behavior. The result of getValue is not the raw value, it is a structure containing the value called functor. They have the map method in common with arrays, but they are just a safety mechanism to prevent accessing non existing vakues. Map in the context of a functor only means "give me the inner value if there is any". The advantage is that, if the value doesn't exist nothing happens , as opposed to the usual "undefined access" errors that are common in JavaScript.
When I get back to home I can give you some better alternatives to your problem, but for now you can just try a double or nested map, and that will work as expected

**Comment by josephgarnier** [comment]
@danielo515 Thanks for the quick reply. A quick and easy alternative is to iterate over the `value` property like this:


```javascript
const category = result
  .getValue("category")
  ?.value.map((tag) => console.log("My tag is: " + tag);
```

It also works very well like this, so you can close the issue if it's not a bug. Have a good dev !
