### ISSUE TITLE
Bug: Editing a form and saving (closing) it closes the forms manager too

### ISSUE THREAD

**Issue by StefanoRausch** [danielo515/obsidian-modal-form#37]
Open the "Manage forms" view, click on `edit` of the form you want to work on -- which correctly gets displayed in a new tab -- and save (close) it results in the forms manager closing as well.

I suggest adding an option in the settings pane to either keep the manager open for further processing of other forms or to close it.

**Comment by StefanoRausch** [comment]
This does not happen if you cancel the form.

**Comment by danielo515** [comment]
I think this no longer happens,  right?

**Comment by StefanoRausch** [comment]
Correct and thank you!
