### ISSUE TITLE
Bug / Feature Request: Fixed header displayed at the bottom of the window when creating a new form

### ISSUE THREAD

**Issue by StefanoRausch** [danielo515/obsidian-modal-form#38]
While https://github.com/danielo515/obsidian-modal-form/issues/11 has been implemented, which is great, the following happens when creating a new form:

![image](https://github.com/danielo515/obsidian-modal-form/assets/1460531/17444b64-55df-41c6-8c4c-498ff90209ee)

When new fields are added, the header shifts to the top:

![image](https://github.com/danielo515/obsidian-modal-form/assets/1460531/fca7c69e-8b89-49be-8d0e-21071b1dec1d)

![image](https://github.com/danielo515/obsidian-modal-form/assets/1460531/192a99b4-206e-42d8-a823-fecf05b16ef2)

I suggest the header be displayed at the top of the window from the start.

**Comment by danielo515** [comment]
Good catch

**Comment by StefanoRausch** [comment]
Nicely resolved! 👍
