### ISSUE TITLE
Feature Request: Allow to dynamically declare which fields to show when opening a form for data capture

### ISSUE THREAD

**Issue by StefanoRausch** [danielo515/obsidian-modal-form#39]
The flexibility of MF is great!

My current template system, implemented with `Templater`, uses several `prompt` and / or `suggester` calls depending on certain conditions. If MF would allow me to "dictate" which fields to present, I could reduce the number of prompts and suggestions to one form. For now, I have to create different forms for different combinations; hence, I am sticking with the "pure" Templater approach.

A possible implementation could be an additional parameter to pass to the `openForm` function: an object declaring the fields to display.

What are your thoughts?

**Comment by StefanoRausch** [comment]
I know that one can define forms "on the fly", but as you state in the README, it is cumbersome and error-prone to do it manually. 😉

**Comment by StefanoRausch** [comment]
The idea is to have a master form containing all possible fields for the general / all-encompassing use case. Some of them are not needed (conditions apply) and would distract or slow down the data capture.

**Comment by danielo515** [comment]
Why not just use different forms? Are they so similar that is not worth even duplicating a form (in case I add that feature) and using a different one?
By the way, do you know that the fields you don't fill are just omitted in the result? Or is the noisy form the problem?

I think this approach is error prone, and I will personally don't use it. 
However, I will not let my principles limit your usage of the plugin 😄 . I will create a new method in the API called `limitForm('form-name', { pick: ['fields','to','pick'], omit: ['fields','to','omit'] })`. Where pick and omit will be mutually exclusive. Will that work for you?

**Comment by StefanoRausch** [comment]
>Why not just use different forms? Are they so similar that is not worth even duplicating a form (in case I add that feature) and using a different one?
> By the way, do you know that the fields you don't fill are just omitted in the result? Or is the noisy form the problem?

Well put, it is the noisiness that can be offsetting, and if I define similar forms for all the possible conditions, it can become a nightmare to choose the right one. 😉 And yes, I am aware of the return value -- very thoughtful of you to implement it that way.

>However, I will not let my principles limit your usage of the plugin 😄 . I will create a new method in the API called limitForm('form-name', { pick: ['fields','to','pick'], omit: ['fields','to','omit'] }). Where pick and omit will be mutually exclusive. Will that work for you?

Exactly what I had in mind. Thank you! I tried it out and it works like a charm. 👏

**Comment by danielo515** [comment]
Wonderful! Glad it works for you.
I may even end up ysing it 😁

**Comment by StefanoRausch** [comment]
Now, with this simple definition, I have a consistent way of calling the forms:

```js
async function openForm(identifier, options = {omit: []}) {
    const api = app.plugins.plugins.modalforms.api;
    
    if (typeof identifier === "string") {
        return await api.limitedForm(identifier, options)
    }
    
    return await api.openModalForm(identifier)
}
```

😄

**Comment by danielo515** [comment]
Happy you found something that works for you. That gave me an idea for docs
about creating a user function in templater to redicw boilerplate. By the
way, I think your if will always resolve to true,  if I inderstood your
intention correctly

**Comment by StefanoRausch** [comment]
Me too. I am already consolidating the various prompt and suggester calls into one form, thanks to your excellent work!

I must disappoint you. 😉 The function works as intended. I have three ways of calling it:

- the full form, no pickings or omissions
- the limited form
- the inline form (your example on the README page)

This is the note which successfully passes the test:

```
<%*
const modal = await self.require.import("[[user.script.modal.open-form.mjs]]")

const everything = await modal.openForm("note-template")
const limited = await modal.openForm("note-template", {omit: ["tag"]})

const inline = await modal.openForm({
	title: 'Example form',
	fields: [
		{
			name: 'name',
			label: 'Name',
			description: 'Your name',
			input: { type: 'text'} ,
		},
		{
			name: 'age',
			label: 'Age',
			description: 'Your age',
			input: { type: 'number'} ,
		},
		{
			name: 'favorite_meal',
			label: 'Favorite meal',
			description: 'Your favorite meal',
			input: { type: 'text'} ,
		},
		{
			name: 'is_family',
			label: 'Is family',
			type: 'toggle',
			description: 'Are you family?',
			required: true,
			input: { type: 'toggle'} ,
		},
	],
})

tR += everything.asString("The title of the note is {{title}} and it is {{tag}}-related.")
tR += limited.asString("The title of the note is {{title}}.")

-%>
```

I have one positive and one negative issue that I have to raise. I will post them later.

**Comment by StefanoRausch** [comment]
This is the more "compact / concise" version, using the [Hindley Millner type system](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system):

```
// openForm :: string | object -> object

async function openForm(identifier, options = {omit: []}) {
    const api = app.plugins.plugins.modalforms.api;
    
    return await typeof identifier == "string"
        ? api.limitedForm(identifier, options)
        : api.openModalForm(identifier)
}

module.exports = {openForm}
```

**Comment by danielo515** [comment]
Ah, another FP fan, glad to see you.

I'm really thinking about extending open-form to do this too, after all is
just a dispatching function for convenience.

**Comment by StefanoRausch** [comment]
Thank you for implementing the enhanced `openForm` function in version `1.15.0`! 👏
