### ISSUE TITLE
Feature request: Multiselect based / constrained by query + mapping

### ISSUE THREAD

**Issue by tsteckenborn** [danielo515/obsidian-modal-form#50]
Would be great to define and restrict multiselect by a query and restrict the values onto them / based on a mapping.

Example:
``` JavaScript
const availableThings = await new Set(app.vault.getMarkdownFiles().filter((file) => file.path.startsWith("XX Something") && app.metadataCache.getFileCache(file).frontmatter?.thing).map((file) => app.metadataCache.getFileCache(file).frontmatter.thing).filter((thing) => thing !== undefined));

const things = (await tp.user.multiSuggester(tp, (project) => project, [...availableThings])).map((thing) => `[[${thing}]]`)
```

**Comment by tsteckenborn** [comment]
Quick win would be Dataquery with Multiselect.

**Comment by danielo515** [comment]
Sorry, isn't this already possible? I have multi-select where you can provide a dataview query as source:
<img width="413" alt="image" src="https://github.com/danielo515/obsidian-modal-form/assets/2270425/924ba2e5-4cf2-4fb7-b3e6-2e461b41520b">

Doesn't that suit your needs?

**Comment by tsteckenborn** [comment]
For me, it doesn't really serve the purpose at the moment. It's more like a free text field for me, no validation or restriction against the values. It would be nice to have the same behaviour as the select or multiselect field, i.e. you have to/can select one of the returned values, but only those.

**Comment by danielo515** [comment]
What about adding this as another option to the select sources? That way you will only be able to select one from the list.

**Comment by tsteckenborn** [comment]
Yeah, that would be nice.

**Comment by StephBoyardee** [comment]
I would like to second this and add that it would nice to be able repeatedly search and choose multiple results. For example, choose Mom Dad and Luke below. This is the same field setup as the dataview field from the example-form btw.
![image](https://github.com/danielo515/obsidian-modal-form/assets/52429365/aa09b3eb-7be4-4583-8de3-5e872a82b04e)
