### ISSUE TITLE
Potential Bug: Copied form not modified, but another form created

### ISSUE THREAD

**Issue by tsteckenborn** [danielo515/obsidian-modal-form#51]
Right now I'm experiencing the issue that a copied button is not modified, but another one created.

- Duplicate a button
- Click edit
- Modify the values, such as the form unique name
- Hit `Save and close`
- Within the menu there's now the "old button copy" and the saved new button with the modified name.

**Comment by danielo515** [comment]
Oh, this is definitely a bug! Thanks for pointing it out
