### ISSUE TITLE
Feature Request: List Input Type

### ISSUE THREAD

**Issue by tsteckenborn** [danielo515/obsidian-modal-form#54]
Could be helpful to have a text input type as a sort of list entry. Could e.g. be an array of strings we could iterate over with templater.

**Comment by danielo515** [comment]
Do you mind giving me an example? I'm afraid I'm not understanding. How is this different from multi select?

**Comment by tsteckenborn** [comment]
Multiselect works - to my understanding - on a selection of existing values. Let's imagine you want to have a contact note, in which while creation you want to add comments as a bullet list, like:

```
### Skills & Interests
- Proficient in X
- Skill 2
- Skill 3
- Prefers design over implementation
```

Or agenda items to meeting minutes
```
| Topic 1 | 10 | 08:00 | 08:10 |
| Topic 2 | 5 | 08:10 | 08:15|
```
The latter, while preferably even more structured, could also work on an array of strings.

Currently - to my understanding - you can not achieve this with multiselect, as it would defy the purpose of selecting something specific.

**Comment by danielo515** [comment]
Ok, I see. So what you want is an input field where you can add any text and, when press enter that value is added as a separate element to a list of values within the same result. Right?

**Comment by tsteckenborn** [comment]
Correct.

**Comment by dannywrayuk** [comment]
Just wanted to +1 this.

I'm using the tags option to add tags to a note (which seems to use multiselect under the hood), but if that tag doesn't already exist then it doesn't appear as an option. This means I can't create new tags.

Having a 'List' type would help make this easier. It would be nice to still be able to provide 'suggestions' but allow anything to be submitted. 

I'm not sure if this even needs to be a new input type, maybe an additional option on multiselect to 'accept-any'.

**Comment by danielo515** [comment]
I agree that just adding an option to allow unknown values will probably be the nest of both worlds. I'll see how hard is to implement

**Comment by dannywrayuk** [comment]
Works great! Thanks a lot :)

**Comment by danielo515** [comment]
Awesome! Happy to read that. Thanks for getting back with the good news
