### ISSUE TITLE
Feature Request: ctrl+enter to submit

### ISSUE THREAD

**Issue by theotheo** [danielo515/obsidian-modal-form#60]
Hello. Thank you for this plugin. It make my workflow more convenient!

So. I wish to submit modal form with my keyboard. I can use Tab to switch to submit button, but it would be great to do it with one keystroke. I guess it's not hard to implement.

**Comment by danielo515** [comment]
Hello @theotheo , thank you for the kind words.
I could take a look at adding support for that
