### ISSUE TITLE
Allow re-order of options in select type (and others)

### ISSUE THREAD

**Issue by stecydube** [danielo515/obsidian-modal-form#64]
I can re-order the fields but not the options from the "select" type.

**Comment by theotheo** [comment]
![image](https://github.com/danielo515/obsidian-modal-form/assets/1499744/a72a85c6-d647-42d5-99a5-1fbbe1bc88d2)
I'm working on this feature. The only difficulty for me right now is to understand how select and multiselect work. Everything else is ready. It wasn't difficult, to be honest

**Comment by danielo515** [comment]
@theotheo that looks very nice. What else do you need? The way they work is exactly the same, with the difference that plain select uses an obiect as value while multi-select only uses strings for now

**Comment by theotheo** [comment]
It can be closed, I suppose.

**Comment by danielo515** [comment]
> It can be closed, I suppose.

Yes! Thanks
