### ISSUE TITLE
BUG: Editing form: the "select/multi-select" type no longer show existing values

### ISSUE THREAD

**Issue by stecydube** [danielo515/obsidian-modal-form#66]
V: 1.16.2

When editing the form, for a select & multi-select (might be others) I no longer see the choices defined for it.

The values are still in the JSON though.

Also, when adding new choices, only the value can be set. The label is not shown anymore nor can it be changed. Still in the JSON though ;)

**Comment by danielo515** [comment]
Yes, the new format of the multi-select only allows for a single value, not label.
Select  should allow you to keep working as expected.
The reason behind this change was that, the multi-select for fixed values never worked, an to make it consistent with the multi-select of dataview I simplified it to just take one value.

Can you paste the JSON that is not working? I may help you migrate it

**Comment by stecydube** [comment]
@danielo515 

Now I get this error when I edit the form:
![image](https://github.com/danielo515/obsidian-modal-form/assets/5737502/434c7039-e42d-4cda-9fb7-bcd88077817a)

Here's the JSON part:

```JSON
        {
          "name": "Genre",
          "label": "Genre",
          "description": "",
          "input": {
            "type": "select",
            "source": "fixed",
            "folder": "",
            "options": [
              {
                "label": "",
                "value": ""
              },
              {
                "label": "Programming",
                "value": "Programming"
              },
              {
                "label": "Scientific",
                "value": "Scientific"
              }
            ]
          }
        },
```

If I remove the "empty" label and value then it fixes it.
Is there a way to have an empty value as a choice?

**Comment by danielo515** [comment]
> @danielo515
> 
> Now I get this error when I edit the form: ![image](https://user-images.githubusercontent.com/5737502/277132281-434c7039-e42d-4cda-9fb7-bcd88077817a.png)
> 
> Here's the JSON part:
> 
> ```json
>         {
>           "name": "Genre",
>           "label": "Genre",
>           "description": "",
>           "input": {
>             "type": "select",
>             "source": "fixed",
>             "folder": "",
>             "options": [
>               {
>                 "label": "",
>                 "value": ""
>               },
>               {
>                 "label": "Programming",
>                 "value": "Programming"
>               },
>               {
>                 "label": "Scientific",
>                 "value": "Scientific"
>               }
>             ]
>           }
>         },
> ```
> 
> If I remove the "empty" label and value then it fixes it. Is there a way to have an empty value as a choice?

In the future, open new issues for new problems, I added a fix for this and I was looking for the issue about it and I was not able to find it 😅
I updated the validation to just allow empty values for now. Do you mind checking?

**Comment by danielo515** [comment]
I consider this bug fixed. Please open it again if it is not
