### ISSUE TITLE
Feuture Request: Activate / Put the cursor in the first modal field for immediate capturing

### ISSUE THREAD

**Issue by StefanoRausch** [danielo515/obsidian-modal-form#7]
This plugin is a great add-on!

Calling the modal forces the user to click on the first or any field to capture the data.

I suggest you activate and put the cursor in the first field to speed up the process for us keyboard-oriented fellows. 😉

**Comment by danielo515** [comment]
I thought about that at first. But many people also gets quite nervous when they get their focus moved automatically. But since most of the current users of the plugin (you and me 😂 ) seems to want it, I will just add that and wait to see if anyone complains

**Comment by StefanoRausch** [comment]
Great and thank you!

**Comment by danielo515** [comment]
In my tests this us already happening. Is it not te same for you? Have you tried in a clean obsidian vault?

**Comment by StefanoRausch** [comment]
Indeed, it is now correctly working as expected.

Thank you!
