### ISSUE TITLE
Frontmatter Issue with Templater?

### ISSUE THREAD

**Issue by SparkleArts** [danielo515/obsidian-modal-form#70]
I created a Template Note for Templater that if you directly create a new Note from a Template it will open the Modal Form and I inserted all the Fields but all the "tp.frontmatter" Variables Implementation doesn't work at all. I get an "undefined" Value.

I attached the .md file for checking it yourself.
[Perk Info.md](https://github.com/danielo515/obsidian-modal-form/files/12895017/Perk.Info.md)

**Comment by SparkleArts** [comment]
I found myself how to make it possible to get the Frontmatter Data from the Modal Form.

**Comment by danielo515** [comment]
Were you expecting the values of frontmatter to become available latter in
the template?
