### ISSUE TITLE
[Feature Request] Restricted Fields

### ISSUE THREAD

**Issue by SparkleArts** [danielo515/obsidian-modal-form#71]
Restricted Fields:
Fields that are only visible/accessable if another field is filled. So you can make more controllable Forms with additional/Optional Fields like in Google Forms.

Required Fields:
Fields that needs to be filled to sumbit the Form.

**Comment by danielo515** [comment]
This are two requests. The former has been on my mind, but it will be
relatively hard with the current form UI, which is based on obsidian
primitives, makes this kind of conditional updating cumbersome, and the
format and rules could get out of hand quickly. I will add it as a future
enhancement,  but in the maybe category.
About the latter,  it has been already requested, and I make you the same
question as I did: for a form whose user is your future self,  what are the
advantages of imposing rules that are coming from your own head?

**Comment by danielo515** [comment]
Required fields has been implemented long time ago.
For tracking the other requirement (restricted fields) I will  continue the conversation on #225
