### ISSUE TITLE
Bug: Select and Multiselect conflicting

### ISSUE THREAD

**Issue by theotheo** [danielo515/obsidian-modal-form#75]
Unfortunately, I have observed what I believe to be unexpected behavior in the `select` element. This issue is also reproducible in the Sandbox Vault, where I have installed only two plugins: `modalform` and `BRAT` (the latter was used to install `modalform`).

![image](https://github.com/danielo515/obsidian-modal-form/assets/1499744/dab9a306-d9f4-461b-a4c9-02d0150f2590)

1) When editing a form, the select does not display a list of previously created values. I can also observe this in the provided example-form. This issue has already been [described](https://github.com/danielo515/obsidian-modal-form/issues/66). 
![image](https://github.com/danielo515/obsidian-modal-form/assets/1499744/c619943e-c0a7-4bc4-8cae-30f71757876a)

It's worth noting that saved options display correctly when using the form.
![image](https://github.com/danielo515/obsidian-modal-form/assets/1499744/e3870a59-32dd-4bb6-a8fa-255739d34be3)

2) Simultaneously, it's not possible to create a new select. The interface allows entering only one string (value), rather than a pair of label-value.

![image](https://github.com/danielo515/obsidian-modal-form/assets/1499744/7e438772-e18a-4297-8dd3-57381e4ac88b)

I suspect that this issue is related to the code modifications made to the `select` to support `multiselect`. And what you know better than me, a `select` needs a list of value-label pairs, whereas a `multiselect` requires just a list of values, as I have mentioned in the [comment](https://github.com/danielo515/obsidian-modal-form/commit/fa5987a93ae7ef7bc6aea60f6273bbcb6e78fcc1#commitcomment-130247846).

**Comment by danielo515** [comment]
Thanks for the detailed report! Will try to fix it as soon as possible

**Comment by danielo515** [comment]
@theotheo can you confirm it works fine again? It is working for me

**Comment by theotheo** [comment]
Confirmed, it's working perfectly now! 👍
