### ISSUE TITLE
[Bug] Previewing the example form on an empty vault not working entirely

### ISSUE THREAD

**Issue by stecydube** [danielo515/obsidian-modal-form#90]
Tried to preview the example form from an empty vault.

Half of the form gets shown, it stops at the "Favorite Book" entry, probably caused by the vault not having a "Books" source folder.

I think it should still continue showing the rest of the form, either not showing this entry or behave like there is nothing in the "Books" folder.

**Comment by theotheo** [comment]
I confirm. I observe the same behavior. However, I didn't pay much attention to it because it seemed like a logical behavior in the absence of the required folder.

**Comment by danielo515** [comment]
I admit that such edge case could be handled better, specially with a better UX.
What if we capture the exception and then just show the form disabled with the error message?
